Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-05, with the labels that each got.

#874 Cleanup & fix jenkins ci
  demos/jobs/README.md
  docs/seed-jobs.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/JdkConfiguratorTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/JdkConfiguratorTest.yml
  pom.xml
Labels: chore

#870 More schema fixes
  plugin/src/main/resources/io/jenkins/plugins/casc/Attribute/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator/schema.jelly
  support/src/main/resources/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator/schema.jelly
Labels: fix

#875 Improvements for Util class and PLUGINS.md
  docs/PLUGINS.md
  docs/REQUIREMENTS.md
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
Labels: documentation

#880 Sort the configuration files for ordered loading of config
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: fix

#877 Move warning sentence into properties file
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.properties
Labels: documentation

#882 Handle null value on stapler converter
  integrations/src/test/java/io/jenkins/plugins/casc/LDAPSecurityRealmTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/LDAPSecurityRealmTestNoSecret.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/LDAPSecurityRealmTestNoSecretExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
Labels: fix

#712 Allow triggering reload with pre-shared secret
  README.md
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadAction.java
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadCrumbExclusion.java
  plugin/src/test/java/io/jenkins/plugins/casc/TokenReloadActionTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/TokenReloadCrumbExclusionTest.java
Labels: feature

#894 Inherit the global Release Drafter configuration
  .github/release-drafter.yml
Labels: chore

#895 Fix role strategy export
  integrations/src/test/java/io/jenkins/plugins/casc/RoleStrategyTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/RoleStrategy1Expected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/RoleBasedAuthorizationStrategyConfigurator.java
Labels: fix

#896 prefer environment variable over global config for config file path
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: fix

#889 use `VersionConverter` instead of lambda
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/VersionConverter.java
Labels: fix

#898 Fix 'git' tool export
  integrations/src/test/java/io/jenkins/plugins/casc/GitToolInstallationTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GitToolInstallationTestExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
Labels: fix

#897 Remove role-strategy from support plugin
  integrations/pom.xml
  support/pom.xml
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/GrantedRoles.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/RoleBasedAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/RoleDefinition.java
Labels: removed

#900 Ignore setters which rely on Maps
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
Labels: fix

#903 Remove left-over job-dsl resources in support plugin
  support/src/main/resources/io/jenkins/plugins/casc/support/jobdsl/FromFileScriptSource/schema.jelly
  support/src/main/resources/io/jenkins/plugins/casc/support/jobdsl/FromUrlScriptSource/schema.jelly
  support/src/main/resources/io/jenkins/plugins/casc/support/jobdsl/InlineGroovyScriptSource/schema.jelly
Labels: chore, skip-changelog

#863 Remove credentials from support plugin
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/CredentialsTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SystemCredentialsTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/SystemCredentialsTest.yml
  support/pom.xml
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/CredentialsRootConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/SystemCredentialsProviderConfigurator.java
  support/src/main/resources/index.jelly
Labels: removed

#904 fix wording
  support/src/main/resources/index.jelly
Labels: skip-changelog
