Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-08, with the labels that each got.

#969 Create documentation for the YAML export feature, document security considerations
  docs/features/configExport.md
  docs/migrate.md
  docs/usageScenarios.md
Labels: documentation

#971 Update mailer-plugin demo
  demos/mailer/README.md
Labels: documentation

#973 Simplify the pull request template and update the checklist
  .github/pull_request_template.md
Labels: chore

#974 Update `@since` in Javadoc for newly introduced APIs
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalMatrixAuthorizationTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/RoleStrategyTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfiguratorException.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Scalar.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithCodeRule.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
Labels: documentation

#975 Reduce logging level for JCasC YAML loading messages
  integrations/src/test/java/io/jenkins/plugins/casc/MailExtTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/ProxyConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: feature

#972 Remove dependency on the interpolatd library which is not used since 1.25
  plugin/pom.xml
Labels: removed

#978 Add IDEA code styles to align IDE with Checkstyle requirements
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: chore

#977 Fix codacy issues
  README.md
  demos/mailer/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/RoleStrategyTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SGECloudTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/Security1446Test.java
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/DefaultConfiguratorRegistry.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/ExtensionConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/ModelConstructor.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java
  plugin/src/main/resources/io/jenkins/plugins/casc/CasCGlobalConfig/config.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator/schema.jelly
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/JenkinsConfigTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/SecretSourceResolverTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/MissingConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/PrimitiveConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/SelfConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/jmh/CascJmhBenchmarkState.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/ExportTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/YamlExportTest.java
Labels: chore

#981 report coverage to codacy
  .travis.yml
Labels: chore

#985 Listed External Workspace Manager in yaml demos
  demos/external-workspace-manager/README.md
Labels: documentation

#988 remove support plugin reference for seed job doc
  docs/seed-jobs.md
Labels: documentation

#990 Add @timja and @oleg-nenashev to the list of maintainers in the plugin metadata
  plugin/pom.xml
Labels: chore

#995 Add known JCasC extensions to readme
  README.md
Labels: documentation

#996 Fix broken sonar config
  demos/sonarqube/README.md
Labels: documentation

#989 [JENKINS-45740] - Inject plugin changelog and logo URLs into the plugin manifest
  plugin/pom.xml
  pom.xml
Labels: chore

#998 Enable Dependabot for the repository
  .dependabot/config.yml
Labels: chore

#1003 add breaking change label
  .github/settings.yml
Labels: chore

#970 Move vault code to hashicorp vault plugin, move tests to integrations
  README.md
  docs/VAULT.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/vault/VaultSecretSourceTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/vault/VaultTestUtil.java
  integrations/src/test/resources/io/jenkins/plugins/casc/vault/vault.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/vault/vaultTest_adminPolicy.hcl
  integrations/src/test/resources/io/jenkins/plugins/casc/vault/vaultTest_cascFile
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/VaultSecretSource.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAppRoleAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAuthenticatorWithExpiration.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultSingleTokenAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultUserPassAuthenticator.java
  plugin/src/test/java/io/jenkins/plugins/casc/DetectMissingVaultPluginTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfiguratorTest.java
Labels: removed

#1005 add dependencies label
  .github/settings.yml
Labels: chore

#1006 Secret sources get initialized too late
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
Labels: bugfix

#1004 switch url to point at GitHub
  CHANGELOG.md
  README.md
  plugin/pom.xml
Labels: chore

#1007 reduce travis builds to master and pull requests
  .travis.yml
Labels: chore

#1008 remove vault-java-driver dependency inside plugin
  plugin/pom.xml
Labels: dependencies

#1020 Dependabot: Ignore Docker, Kubernetes, Declarative Pipeline and Custom Tools plugins which have custom group IDs
  .dependabot/config.yml
Labels: chore

#1022 Fix Dependabot :facepalm:
  .dependabot/config.yml
Labels: skip-changelog

#1034 Update job-dsl example as id is required
  demos/jobs/multibranch-github.yaml
Labels: documentation
