Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-10, with the labels that each got.

#1106 Validate proxy demo with the integrations framework
  integrations/src/test/java/io/jenkins/plugins/casc/ProxyTest.java
Labels: chore

#1107 Validate external-workspace-manager demo with the integrations framework
  demos/external-workspace-manager/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ExternalWorkspaceManagerTest.java
Labels: chore

#1108 Move git tools ITs to the demos
  demos/git/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/GitToolInstallationTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GitToolInstallationTest.yml
Labels: chore

#1068 Add another method for configuration reload
  README.md
Labels: documentation, hacktoberfest

#1114 Validate mesos demo with the integrations framework
  demos/mesos/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/MesosTest.java
Labels: chore

#1123 Validate simple-theme demo with the integrations framework
  demos/simple-theme-plugin/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/SimpleThemeTest.java
Labels: chore, hacktoberfest

#1112 Validate sbt demo with the integrations framework
  demos/sbt/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/SbtTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/SbtTestExpected.yml
Labels: chore, hacktoberfest

#1116 Use schema library in test scope only
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/SchemaGeneration.java
  plugin/src/test/java/io/jenkins/plugins/casc/SchemaGenerationTest.java
Labels: dependencies

#1110 Validate external-workspace-manager demo with the integrations framework
  integrations/pom.xml
Labels: chore, hacktoberfest

#1117 Validate warnings demo with the integrations framework
  demos/warnings/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/WarningsTest.java
Labels: chore, hacktoberfest

#1122 Minor improvements to array creation and one unit test
  integrations/src/test/java/io/jenkins/plugins/casc/CredentialsTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/RootElementConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSource.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/PrimitiveConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithReadmeRule.java
Labels: chore

#1125 fixes integrations dependencies
  integrations/pom.xml
Labels: skip-changelog

#1131 Change log level to WARN when configuration sources could not be applied
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
Labels: chore, hacktoberfest

#1119 Validate statistics-gatherer demo with the integrations framework
  demos/statistics-gatherer/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/StatisticsGathererTest.java
Labels: chore, hacktoberfest

#1132 README: Change the changelog badge label to make it more explicit
  README.md
Labels: documentation

#1118 Validate slack demo with the integrations framework
  demos/slack/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/SlackTest.java
Labels: chore, hacktoberfest

#1111 Validate keycloak demo with the integrations framework
  demos/keycloak/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/KeycloakTest.java
Labels: chore, hacktoberfest

#1130 Updated pom file to set Project description and URL
  plugin/pom.xml
  pom.xml
Labels: chore, hacktoberfest

#1109 Validate github demo with the integrations framework
  demos/github/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/GitHubTest.java
Labels: chore, hacktoberfest

#1144 Update error message in RoundTripAbstractTest
  plugin/src/test/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: chore, hacktoberfest

#1143 Move Handling Secrets to a separate page, add docs for CredentialsProvider and encrypted strings
  README.md
  docs/features/secrets.adoc
Labels: documentation, hacktoberfest

#1152 Remove run locally intellij idea cli from main readme add to docs contributing
  README.md
  docs/CONTRIBUTING.md
Labels: documentation, hacktoberfest

#1153 Add demo for the NodeJS plugin
  demos/nodejs/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/NodeJSTest.java
Labels: documentation, hacktoberfest

#1156 #1149 Invert the LDAP example on the README page
  README.md
Labels: documentation, hacktoberfest

#1155 Move Trigger Configuration Reload to a new feature page #1150
  README.md
  docs/features/configurationReload.md
Labels: documentation, hacktoberfest

#1163 Deprecate misspelled Mapping.putIfNotEmpry in favor of Mapping.putIfNotEmpty
  plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java
Labels: bugfix

#1060 Add Documentation for Fields in the JSON Schema
  plugin/src/main/java/io/jenkins/plugins/casc/SchemaGeneration.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/SchemaGenerationTest.java
Labels: dev-tools, feature

#1160 Introduce a SecretSource implementation for .properties file
  docs/features/secrets.adoc
  integrations/src/test/java/io/jenkins/plugins/casc/PropertiesSecretSourceTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/PropertiesSecretSourceTest.yaml
  integrations/src/test/resources/io/jenkins/plugins/casc/secrets.properties
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/PropertiesSecretSource.java
Labels: feature, hacktoberfest

#1157 #1147 - Add Readme to the demos directory
  demos/README.md
Labels: documentation, hacktoberfest

#1183 close yaml reader after use 😰
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java
Labels: bugfix

#1192 fix mvn flags on powershell
  .github/workflows/maven.yml
Labels: chore
