Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-09, with the labels that each got.

#1029 Update Project meetings information and move it to CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#1047 Use BOM for dependency management inside integrations tests
  integrations/pom.xml
Labels: chore

#1050 Fix PR template after moving description to top
  .github/pull_request_template.md
Labels: skip-changelog

#1049 Fix space in logs
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
Labels: bugfix

#1053 Allow `@CheckForNull` annotations to override `@ParametersAreNonnullByDefault` in DataBoundContructor
  integrations/src/test/resources/io/jenkins/plugins/casc/SonarQubeTest.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/nonnullparampackage/PackageParametersNonNullCheckForNull.java
Labels: bugfix

#980 JCasC JSONSchema Generation and Testing
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/SchemaGeneration.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/test/java/io/jenkins/plugins/casc/SchemaGenerationTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
  plugin/src/test/resources/io/jenkins/plugins/casc/invalidSchemaConfig.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/validSchemaConfig.yml
Labels: dev-tools

#1069 Remove old jelly schema and usages
  docs/features/jsonSchema.md
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/resources/io/jenkins/plugins/casc/Attribute/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/BaseConfigurator/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/DescribableAttribute/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/ConfigurableConfigurator/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator/schema.jelly
Labels: dev-tools, removed

#1071 [JENKINS-57557] Add integration test with github-branch-source
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalLibrariesTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalLibrariesGitHubTest.yml
Labels: chore

#1055 Move YAML examples from integration tests to the demos, ensure all demos have test coverage
  demos/active-directory/README.md
  demos/artifact-manager-s3/README.md
  demos/jenkins/jenkins.yaml
  demos/mailer/README.md
  demos/sonarqube/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ActiveDirectoryTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/ArtifactManagerS3Test.java
  integrations/src/test/java/io/jenkins/plugins/casc/MailerTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/RoundTripMailerTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SonarQubeTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/ActiveDirectoryTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/MailerTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/SonarQubeTest.yml
  plugin/pom.xml
  plugin/src/test/java/io/jenkins/plugins/casc/misc/ConfiguredWithReadme.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredRule.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithCodeRule.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithReadmeRule.java
  plugin/src/test/resources/io/jenkins/plugins/casc/GetConfiguratorsTest.yml
Labels: chore

#1075 BOM 3
  integrations/pom.xml
Labels: chore

#1081 Validate build_agents demo within the integrations submodule
  demos/build_agents/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/BuildAgentsTest.java
Labels: chore

#1079 Remove duplicate github-branch-source dep in integration tests
  integrations/pom.xml
Labels: chore, skip-changelog

#1083 Validate config-file-provider demo with the integrations framework
  demos/config-file-provider/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ConfigFileProviderTest.java
Labels: chore

#1084 Validate docker-plugin demo with the integrations framework
  demos/docker/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/DockerCloudTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/DockerCloudTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/DockerCloudTest1.yml
Labels: chore

#1080 Validate Artifactory demo within the integrations submodule
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ArtifactoryTest.java
Labels: chore

#1085 Validate ec2-plugin demo with the integrations framework
  demos/ec2/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/EC2CloudTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/EC2Cloud.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/EC2CloudAMIType.yml
Labels: chore

#1087 Validate gitlab demo with the integrations framework
  demos/gitlab/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/GitLabConfigurationTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GitLabTest.yml
Labels: chore

#1088 Move jira ITs to the demos
  demos/jira/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/JiraTest.java
Labels: chore

#1089 Move mercurial ITs to the demos
  demos/mercurial/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/MercurialTest.java
Labels: chore

#1090 Move JDK ITs to the demos
  demos/jdk/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/JdkConfiguratorTest.java
Labels: chore

#1086 Validate github-oath demo with the integrations framework
  demos/github-oauth/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/GithubOAuthTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GithubOAuth.yml
Labels: chore

#1091 Move matrix-auth ITs to the demos
  demos/matrix-auth/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalMatrixAuthorizationTest.java
Labels: chore
