Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-04, with the labels that each got.

#810 Re-parse vault configuration on every configure() call
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/VaultSecretSource.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAppRoleAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAuthenticatorWithExpiration.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultUserPassAuthenticator.java
Labels: feature

#823 Hint what version of config-file-provider is needed for JCasC
  demos/config-file-provider/README.md
Labels: documentation

#778 fix JSON schema issues
  plugin/src/main/resources/io/jenkins/plugins/casc/Attribute/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/DescribableAttribute/schema.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator/schema.jelly
Labels: fix

#827 Add more test coverage for ProxyConfigurator
  plugin/src/test/java/io/jenkins/plugins/casc/core/ProxyConfiguratorTest.java
Labels: test

#830 updated badges
  README.md
  docs/PLUGINS.md
  docs/REQUIREMENTS.md
Labels: chore

#831 docs prettier formatting & cleanup
  .ci/Jenkinsfile
  .ci/README.md
  .github/ISSUE_TEMPLATE/3-plugin-compatibility.md
  README.md
  demos/config-file-provider/README.md
  demos/credentials/README.md
  demos/ec2/README.md
  demos/github/README.md
  demos/gitlab/README.md
  demos/gitscm/README.md
  demos/global-matrix-auth/README.md
  demos/graphite/README.md
  demos/jenkins/README.md
  demos/jobs/README.md
  demos/ldap/README.md
  demos/mailer/README.md
  demos/mesos/README.md
  demos/proxy/README.md
  demos/sbt/README.md
  demos/slack/README.md
  demos/statistics-gatherer/README.md
  demos/terraform/README.md
  demos/tfs/README.md
  demos/workflow-cps-global-lib/README.md
  docs/CONTRIBUTING.md
  docs/IMPLEMENTATION.md
  docs/PLUGINS.md
  docs/REQUIREMENTS.md
  docs/VAULT.md
  docs/usageScenarios.md
  docs/vault/setup-vault-using-docker.md
Labels: documentation

#834 Allow loading of a single file in a hidden folder
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: feature

#836 Add view configuration feature
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/viewExport.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.css
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.js
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/admin.yml
Labels: feature

#838 make export great again by fixing NPE in describe
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/JenkinsConfiguratorCloudSupportTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/ProxyConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
  plugin/src/test/resources/io/jenkins/plugins/casc/impl/configurators/DataBoundDescriptorNonNull.yml
Labels: fix

#843 fix view configuration button and cleanup css styling
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/index.css
Labels: fix

#846 add ConfiguredWithCode as class rule
  plugin/src/test/java/io/jenkins/plugins/casc/JenkinsConfiguredWithCodeRuleClassRuleTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/ConfiguredWithCode.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/JenkinsConfiguredWithCodeRule.java
Labels: feature

#847 Fix ssh-credential to be optional
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/DirectEntryPrivateKeySourceConfigurator.java
Labels: fix

#849 fix readability alerts reported by LGTM
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAppRoleAuthenticator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultAuthenticatorWithExpiration.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/vault/VaultUserPassAuthenticator.java
Labels: chore

#814 compare collection in Attribute
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
Labels: chore

#852 Add copy-to-clipboard prism plugin to viewExport
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.css
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.js
Labels: enhancement, feature

#851 Add docs for testing export of configuration
  docs/PLUGINS.md
Labels: documentation

#854 add reverted as an excluded label
  .github/release-drafter.yml
Labels: chore

#853 Use CSS `user-select` to achieve easy copy paste
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/viewExport.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.css
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/prism.js
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/viewExport.css
Labels: feature

#859 Update labels usage
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/release-drafter.yml
  .github/stale.yml
Labels: chore

#845 Remove matrix-auth from support plugin
  demos/global-matrix-auth/README.md
  integrations/pom.xml
  support/pom.xml
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/GlobalMatrixAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/MatrixAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/ProjectMatrixAuthorizationStrategyConfigurator.java
Labels: removed

#857 fix unit test on windows
  .gitattributes
  .travis.yml
  demos/graphite/README.md
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: test

#864 add W.I.P hint in pull request template
  .github/pull_request_template.md
Labels: chore

#865 Adding saml plugin config in demo
  demos/saml/README.md
Labels: documentation

#860 Update plugin export docs
  .travis.yml
  docs/PLUGINS.md
  plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java
Labels: documentation

#862 remove ssh credentials from support plugin
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/CredentialsTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SystemCredentialsTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/SystemCredentialsTest.yml
  support/pom.xml
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/DirectEntryPrivateKeySourceConfigurator.java
Labels: removed

#861 Remove job-dsl from support plugin
  integrations/pom.xml
  support/pom.xml
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/ConfigurableScriptSource.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/FromFileScriptSource.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/FromUrlScriptSource.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/InlineGroovyScriptSource.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/ScriptSource.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator.java
Labels: removed
