Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-07, with the labels that each got.

#936 Allow partial selection in export viewer.
  plugin/src/main/resources/io/jenkins/plugins/casc/assets/viewExport.css
Labels: feature

#940 Properly export floating-point values
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Scalar.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfiguratorTest.java
Labels: bugfix

#941 support multi-line string export using literal style
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Scalar.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/multi-line1.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/multi-line2.yml
Labels: feature

#945 Prevent NumberFormatException in system log when exporting the JSON schema
  plugin/src/main/resources/io/jenkins/plugins/casc/Attribute/schema.jelly
Labels: bugfix

#946 Fix `ToolDefaultPropertiesExportBlacklistTest#export_tool_configuration()` when building the plugin on Windows
  integrations/src/test/java/io/jenkins/plugins/casc/ToolDefaultPropertiesExportBlacklistTest.java
Labels: test

#952 Add an issue template for questions and support requests
  .github/ISSUE_TEMPLATE/4-support
Labels: chore

#953 Rename 4-support to 4-support.md
  .github/ISSUE_TEMPLATE/4-support.md
Labels: skip-changelog

#956 [JENKINS-52906] - Update JIRA Plugin test dependency to verify the JCasC compatibility and support writing roundtrip tests
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/JiraTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/JiraTest.yml
Labels: test

#957 Print warning when a secret variable cannot be resolved during import
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/test/java/io/jenkins/plugins/casc/SecretSourceResolverTest.java
Labels: feature

#958 Remove Markdown from the Support Issue template
  .github/ISSUE_TEMPLATE/4-support.md
Labels: skip-changelog

#950 DataBoundConfigurator: do not throw NullPointerException with empty collection
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfiguratorTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/ClassParametersAreNonnullByDefault.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/NonnullParameterConstructor.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/nonnullparampackage/PackageParametersAreNonnullByDefault.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/nonnullparampackage/package-info.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/nonnull/package-info.java
Labels: feature

#966 Issue #965 - Remove the obsolete plugin management section from the JCasC reference generator screenshot
  images/reference.png
Labels: documentation
