Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-03, with the labels that each got.

#796 Update plugin dev guide with ConfiguredAsCode rule
  docs/PLUGINS.md
Labels: documentation

#802 update kubernetes-helm docs
  demos/kubernetes-helm/README.md
Labels: documentation

#794 add Release drafter
  .github/release-drafter.yml
Labels: chore

#792 YAML Sources code cleanup
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/cli/ApplyConfigurationCommand.java
  plugin/src/main/java/io/jenkins/plugins/casc/cli/CheckConfigurationCommand.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java
Labels: chore

#799 Include only needed classes in test jar
  plugin/pom.xml
Labels: fix

#786 only log deprecation if CASC_VAULT_PATH is present
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/VaultSecretSource.java
Labels: fix

#791 Use NonNull and CheckForNull from SpotBugs
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfiguratorException.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfiguratorRegistry.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/MavenConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/NoneSecurityRealmConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/UnsecuredAuthorizationStrategyConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/DefaultConfiguratorRegistry.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/ConfigurableConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/EnumConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/ExtensionConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/PrimitiveConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/SelfConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/util/PermissionFinder.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfiguratorTest.java
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/CredentialsRootConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/DirectEntryPrivateKeySourceConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/credentials/SystemCredentialsProviderConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/GlobalMatrixAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/MatrixAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/ProjectMatrixAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/GrantedRoles.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/RoleBasedAuthorizationStrategyConfigurator.java
  support/src/main/java/io/jenkins/plugins/casc/support/rolestrategy/RoleDefinition.java
Labels: chore

#783 Demo docs for Sbt tool configuration
  demos/sbt/README.md
Labels: documentation

#805 add missing annotation
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/CasCGlobalConfig.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/JenkinsConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/UpdateSiteConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/DefaultConfiguratorRegistry.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/SelfConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Scalar.java
  snakeyaml/src/main/java/io/jenkins/plugins/casc/snakeyaml/Yaml.java
  snakeyaml/src/main/java/io/jenkins/plugins/casc/snakeyaml/reader/UnicodeReader.java
  snakeyaml/src/main/java/io/jenkins/plugins/casc/snakeyaml/representer/SafeRepresenter.java
  support/src/main/java/io/jenkins/plugins/casc/support/matrixauth/MatrixAuthorizationStrategyConfigurator.java
Labels: chore

#674 Describable will give a warning on multiple implementations of a symbol
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/DuplicateKeyDescribableConfiguratorTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/impl/configurators/DuplicateKeyDescribableConfigure.yml
  support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator.java
Labels: feature

#807 add travis ci
  .travis.yml
Labels: chore

#806 Don't ignore values if default on export
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfigurator.java
Labels: fix

#808 support building against recent Jenkins LTS and JDK 11
  .travis.yml
  Jenkinsfile
  integrations/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Sequence.java
  plugin/src/spotbugs/excludesFilter.xml
  plugin/src/test/java/io/jenkins/plugins/casc/BackwardCompatibilityTest.java
  pom.xml
Labels: chore

#804 Keep cloud agents after configuration
  plugin/src/main/java/io/jenkins/plugins/casc/core/JenkinsConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/JenkinsConfiguratorCloudSupportTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/core/JenkinsConfiguratorCloudSupportTest.yml
Labels: fix

#788 Support encrypted passwords for local security realm
  demos/role-strategy-auth/role-strategy-auth.yaml
  plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfiguratorTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfiguratorTest.yml
Labels: feature

#803 Improve GitHub templates, move changelog to GitHub release tab, cleanup old docs
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-report-bug.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-plugin-compatibility.md
  .github/issue_template.md
  .github/pull_request_template.md
  CHANGELOG.md
  COMPATIBILITY.adoc
  CONTRIBUTING.md
  README.md
  docs/COMPATIBILITY.md
  docs/CONTRIBUTING.md
  docs/IMPLEMENTATION.md
  docs/RELEASE_NOTES.md
  docs/REQUIREMENTS.md
  images/BraceYourselves.jpg
  images/CasC_new-03.png
Labels: documentation

#812 code cleanup
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/UpdateCenterConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/ExtensionConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
Labels: chore

#813 fix null pointer on mapping clone
  plugin/src/main/java/io/jenkins/plugins/casc/model/Mapping.java
  plugin/src/test/java/io/jenkins/plugins/casc/model/MappingTest.java
Labels: fix

#811 add service account credential to advanced k8s example
  demos/kubernetes/adv_config.yml
Labels: documentation
