Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2019-06, with the labels that each got.

#905 Fix node properties export
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalNodePropertiesTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTestExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
Labels: fix

#906 Cleanup references to support plugin after removal
  README.md
  demos/config-file-provider/README.md
  demos/global-matrix-auth/README.md
  integrations/pom.xml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalMatrixStrategy.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/ProjectMatrixStrategy.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/util/PermissionFinder.java
  plugin/src/test/java/io/jenkins/plugins/casc/impl/configurators/MissingConfiguratorTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/impl/configurators/MissingConfiguratorTest.yml
  pom.xml
  support/pom.xml
  support/src/main/resources/index.jelly
Labels: chore

#907 update doc with required version for credentials and role-strategy
  demos/credentials/README.md
  demos/role-strategy-auth/README.md
Labels: documentation

#911 Prevent null pointer when non-first yml file is empty.
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/aNonEmpty.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/empty.yml
Labels: fix

#908 [JENKINS-57761] - Add abstract test for export/configure roundtrip
  integrations/src/test/java/io/jenkins/plugins/casc/RoundTripMailerTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: test

#916 Fix ProxyConfigurator does not resolve secrets
  plugin/src/main/java/io/jenkins/plugins/casc/core/ProxyConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/core/ProxyConfiguratorTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/core/ProxyWithSecrets.yml
Labels: fix

#920 [ad-hoc] EC2 Plugin v1.42 parameters deprecated
  demos/ec2/README.md
Labels: documentation

#927 Link newbie-friendly issues in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#925 [JENKINS-57122] - Add blacklist for defaultProperties on tools
  integrations/src/test/java/io/jenkins/plugins/casc/JdkConfiguratorTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/ToolDefaultPropertiesExportBlacklistTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/JdkConfiguratorTestExpected.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/ToolDefaultPropertiesExportBlacklist.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/ToolDefaultPropertiesExportBlacklistExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/Blacklist.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
Labels: feature

#932 [JENKINS-57604] - HeteroDescribableConfigurator now properly matches descriptors for subclass fields, e.g. for Git plugin's SCM Browsers
  integrations/src/test/java/io/jenkins/plugins/casc/GitTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GitTest.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
Labels: bugfix

#929 Prevent failure of `ConfigurationAsCodeTest.java#init_test_from_accepted_sources()` when building on Windows
  plugin/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: test

#935 Remove link to plugin compatibility tracker
  .github/ISSUE_TEMPLATE/3-plugin-compatibility.md
Labels: chore, skip-changelog
