Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-04, with the labels that each got.

#1302 Improve SecretSource Javadoc
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSource.java
Labels: documentation

#1352 remove wip hint
  .github/pull_request_template.md
Labels: skip-changelog

#1358 set category name to Configuration for Jenkins v2.226+
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  test-harness/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: feature

#1359 Fix compatibility with core 2.231
  plugin/pom.xml
Labels: bugfix

#1362 Update to 4.0 parent pom
  pom.xml
Labels: dependencies
