Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-07, with the labels that each got.

#1436 bump dependency management
  integrations/pom.xml
Labels: skip-changelog

#1408 SecretResolver support file and base64 variable expansion
  .gitattributes
  .gitignore
  demos/artifactory/README.md
  demos/credentials/README.md
  demos/credentials/credentials.yaml
  demos/jenkins/jenkins.yaml
  demos/ldap/README.md
  docs/features/secrets.adoc
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/CredentialsReadmeTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/mysecretfile.txt
  integrations/src/test/resources/io/jenkins/plugins/casc/private-key.pem
  integrations/src/test/resources/io/jenkins/plugins/casc/test.p12
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/PrimitiveConfigurator.java
  plugin/src/test/java/io/jenkins/plugins/casc/SecretSourceResolverTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/jmh/BenchmarkRunner.java
  plugin/src/test/java/io/jenkins/plugins/casc/jmh/benchmarks/ConfigureBenchmark.java
  plugin/src/test/java/io/jenkins/plugins/casc/jmh/benchmarks/SecretSourceResolverBenchmark.java
  plugin/src/test/resources/io/jenkins/plugins/casc/secret.json
  plugin/src/test/resources/io/jenkins/plugins/casc/some secret.json
Labels: feature

#1433 Consolidate SecretSource options into secrets.adoc
  README.md
  docs/features/secrets.adoc
Labels: documentation

#1434 Fix a internal link to PLUGINS.md. Fix some typos.
  docs/COMPATIBILITY.md
  docs/IMPLEMENTATION.md
Labels: documentation

#1435 change properties secrets env to `SECRETS_FILE`
  docs/features/secrets.adoc
  integrations/src/test/java/io/jenkins/plugins/casc/PropertiesSecretSourceTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/PropertiesSecretSource.java
Labels: breaking, chore
