Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-11, with the labels that each got.

#1492 [DEMOS] Add more examples to help with bitbucket casc
  demos/jobs/bitbucket.yaml
Labels: documentation

#1464 Update the Docker plugin demo to use the "jenkins/agent" image instead of the deprecated one
  demos/docker/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/DockerCloudTest.java
Labels: documentation

#1526 Add `decodeBase64` substitutor for reading base64-encoded variables
  demos/credentials/README.md
  docs/features/secrets.adoc
  integrations/src/test/java/io/jenkins/plugins/casc/SSHCredentialsTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/SSHCredentialsTest_Multiline_Key.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/SSHCredentialsTest_Singleline_Key.yml
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
Labels: feature

#1525 Hacktoberfest - [JENKINS-62446]Test coverage for tool.maven and tool.mavenGlobalConfig
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalToolGlobalMavenTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalToolGlobalMavenTest.yaml
Labels: chore, hacktoberfest-accepted
