Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-03, with the labels that each got.

#1296 Allow users with Overall/SystemRead permission to view configuration, schema, and documentation
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  pom.xml
Labels: feature

#1308 Allow multiple symbols when importing, exporting first one
  integrations/src/test/java/io/jenkins/plugins/casc/PipelineModelDefinitionSymbolTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/PipelineModelDefinitionSymbol.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/PipelineModelDefinitionSymbolExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/GlobalConfigurationCategoryConfigurator.java
Labels: bugfix

#1318 Validate MSBuild plugin compatibility
  demos/msbuild/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/MSBuildTest.java
Labels: test

#1319 Documentation only: replace JENKINS_ROOT with JENKINS_HOME
  README.md
  test-harness/src/main/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: documentation

#1321 Add Azure KeyVault to secrets doc
  docs/features/secrets.adoc
Labels: documentation

#1328 Add integration test for MSTestRunner
  demos/mstestrunner/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/MSTestRunnerTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/ToolDefaultPropertiesExportBlacklistExpected.yml
Labels: documentation, test

#1262 [JENKINS-51856] Apply configuration before the jobs are loaded
  README.md
  integrations/src/test/resources/io/jenkins/plugins/casc/init.yml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
Labels: feature

#1338 Remove vault integration test
  Jenkinsfile
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/vault/VaultSecretSourceTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/vault/VaultTestUtil.java
Labels: test

#1344 Add Gitter Q&A tab to the New Issue dialog
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore
