Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-02, with the labels that each got.

#1268 Fix the version specification for Jenkins 2.199
  README.md
Labels: documentation

#1270 Added example for credentials certificate
  demos/credentials/credentials.yaml
Labels: documentation

#1273 Update test to match latest plugin version
  integrations/pom.xml
Labels: dependencies

#1274 Update the integration test for active-directory
  demos/active-directory/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ActiveDirectoryTest.java
Labels: dependencies

#1276 Add integration test for pipeline-model-definition-plugin
  demos/pipeline-model-definition/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/PipelineModelDefinitionTest.java
Labels: documentation, test

#1280 Stop exporting users and throwing nullpointer
  plugin/src/main/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfigurator.java
  test-harness/src/test/java/io/jenkins/plugins/casc/JenkinsConfiguredWithCodeRuleClassRuleTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/core/HudsonPrivateSecurityRealmConfiguratorTest.java
Labels: bugfix

#1289 Upgrade metrics-plugin
  integrations/pom.xml
Labels: dependencies

#1282 Prevent null pointer when exporting file credentials
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/CredentialsTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalCredentials.yml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
Labels: bugfix
