Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-10, with the labels that each got.

#1474 Documentaion section moved up
  README.md
Labels: documentation, hacktoberfest

#1493 [1448] Fix admin monitor UI
  plugin/src/main/resources/io/jenkins/plugins/casc/ObsoleteConfigurationMonitor/message.jelly
Labels: bugfix

#1494 Bump parent pom
  pom.xml
Labels: dependencies
