Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-01, with the labels that each got.

#1027 Schema Generation for nested yml configurations
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/AzureKeyVaultTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SlackTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/SonarQubeTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/azureKeyVault.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/slackSchema.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/sonarSchema.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/sonarSchemaFull.yml
  plugin/src/main/java/io/jenkins/plugins/casc/Attribute.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/SchemaGeneration.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  test-harness/src/test/java/io/jenkins/plugins/casc/SchemaGenerationSanitisationTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/SchemaGenerationTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/attributesNotFlattenedToTop.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/invalidBaseConfig.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/invalidToolBaseConfig.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/validJenkinsBaseConfig.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/validJenkinsBaseConfigWithSymbol.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/validSchemaConfig.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/validSelfConfig.yml
Labels: dev-tools, feature

#1243 Trying to diagnose some flaky tests
  test-harness/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: test

#1241 Update ci to include code coverage after #1215
  .github/workflows/maven.yml
  .travis.yml
  codecov.yml
  integrations/pom.xml
  pom.xml
Labels: chore

#1245 Checkstyle ignore release.properties
  .mvn/checkstyle-suppressions.xml
  pom.xml
Labels: chore

#1249 Automatically request code reviews from all JCasC plugin developers
  .github/CODEOWNERS
Labels: chore
