Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2020-05, with the labels that each got.

#1372 Add support for symbolic linked directories
  README.md
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  test-harness/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
Labels: feature

#1368 [JENKINS-58093] - Support for LabelAtoms
  plugin/src/main/java/io/jenkins/plugins/casc/core/JenkinsConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/LabelAtomConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/LabelAtomPropertyConfigurator.java
  test-harness/src/test/java/io/jenkins/plugins/casc/core/JenkinsConfiguratorTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/ConfigureLabels.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/ConfigureNodes.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/ExpectedLabelsConfiguration.yml
Labels: feature

#1387 HeteroDescribableConfigurator fix for interface as a target
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
Labels: bugfix

#1397 Add apiUri parameter for github enterprise example case
  demos/jobs/multibranch-github.yaml
Labels: documentation

#1380 bump terraform to 1.0.10
  demos/terraform/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/TerraformTest.java
Labels: dependencies

#1381 Bump config-file-provider-plugin to 3.6.3
  integrations/pom.xml
Labels: dependencies

#1394 sort Attributes and RootElementConfigurator according to Extension ordinal
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/RootElementConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/JenkinsConfigurator.java
Labels: bugfix

#1399 Correct false positive code coverage
  .github/workflows/maven.yml
  .travis.yml
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadAction.java
  test-harness/src/test/java/io/jenkins/plugins/casc/TokenReloadActionTest.java
Labels: chore

#1375 Allow configuring max aliases for a collection
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
  test-harness/src/test/java/io/jenkins/plugins/casc/YamlMaxAliasesCollection.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/maxAliasesLimit.yml
Labels: bugfix

#1398 Close those file handles 😅
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/StreamReaderWithSource.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlReader.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/YamlSourceTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/YamlReaderTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/folder/jenkins.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/folder/jenkins2.yml
Labels: bug

#1402 Escape newSource field when checking it's value via Ajax.
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
Labels: bugfix
