Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2021-04, with the labels that each got.

#1589 Update broken link in Secrets documentation
  docs/features/secrets.adoc
Labels: documentation

#1594 Remove guava and guice usage from the plugin
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadAction.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/DefaultConfiguratorRegistry.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DescriptorConfigurator.java
  pom.xml
Labels: chore

#1591 Integration test with Jenkins 2.277.3
  integrations/pom.xml
Labels: chore

#1596 Revert "Replace Guava's cache with Caffeine."
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/impl/DefaultConfiguratorRegistry.java
  pom.xml
Labels: bug
