Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2021-08, with the labels that each got.

#1657 Add intellij run configuration
  .run/start jenkins.run.xml
Labels: chore

#1653 Allow reloading configuration with Overall/Manage permission
  .idea/codeStyles/Project.xml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/test/java/io/jenkins/plugins/casc/permissions/Action.java
  plugin/src/test/java/io/jenkins/plugins/casc/permissions/PermissionsTest.java
  pom.xml
Labels: feature

#1676 Minor typo fix in readme
  demos/jobs/README.md
Labels: documentation
