Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2021-01, with the labels that each got.

#1543 Update integration tests to use latest LTS line
  demos/warnings/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/WarningsTest.java
Labels: chore

#1553 (docs) update README.md
  README.md
Labels: documentation

#1556 Add possibility to reload secrets from properties file with JCasC reload
  integrations/src/test/java/io/jenkins/plugins/casc/PropertiesSecretSourceTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/PropertiesSecretSource.java
Labels: feature

#1558 Test with Jenkins 2.263.3
  integrations/pom.xml
Labels: chore
