Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2021-12, with the labels that each got.

#1802 Prepare sunset of superseded PNG icons from core
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
Labels: bug

#1791 Add Gitea demo configuration for jobs
  demos/jobs/README.md
  demos/jobs/gitea.yaml
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/GiteaOrganisationFolderTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/GiteaServerTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/SeedJobTest_withGiteaOrganisation.yml
  integrations/src/test/resources/plugins/branch-api.jpi
  integrations/src/test/resources/plugins/cloudbees-folder.jpi
  integrations/src/test/resources/plugins/scm-api.jpi
  integrations/src/test/resources/plugins/structs.jpi
Labels: documentation

#1812 Modernize GH Action CI
  .github/workflows/maven.yml
Labels: chore
