Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-04, with the labels that each got.

#1956 add developer label
  .github/CODEOWNERS
  .github/settings.yml
Labels: chore

#1955 Update plugin parent POM and BOM
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/EssentialsTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/MailExtTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/MailExtTest.yml
  pom.xml
Labels: developer

#1960 doc: update Docker Cloud examples
  demos/docker/README.md
  demos/jenkins/jenkins.yaml
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/DockerCloudTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/DockerCloudTest2.yml
Labels: documentation

#1964 Set permissions for GitHub actions
  .github/workflows/maven.yml
Labels: chore
