Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-10, with the labels that each got.

#1603 Adding Demo for View-Job-Filters plugin
  demos/view-job-filters/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/ViewJobFiltersTest.java
Labels: test

#2146 Updating broken link
  docs/IMPLEMENTATION.md
Labels: documentation

#2147 Replace commons-text with Jenkins plugin
  integrations/pom.xml
  plugin/pom.xml
  pom.xml
Labels: enhancement

#2149 Removed now obsolete spotbugs exclude
  plugin/src/spotbugs/excludesFilter.xml
Labels: chore

#2148 [Docs] CONTRIBUTING.md Remove java 8 remarks - java 11 works
  docs/CONTRIBUTING.md
Labels: chore
