Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-08, with the labels that each got.

#2087 Remove deprecated java.level from docs
  docs/PLUGINS.md
Labels: documentation

#2095 build: Update bom to oldest included version
  plugin/pom.xml
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/DockerSecretSource.java
  pom.xml
  test-harness/pom.xml
  test-harness/src/test/java/io/jenkins/plugins/casc/core/JenkinsConfiguratorTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/ExpectedLabelsConfiguration.yml
Labels: chore

#2093 Initiate new LTS baseline 2.361.x
  integrations/pom.xml
Labels: chore

#2108 fix: Restore broken master branch build
  test-harness/src/test/java/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfiguratorTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfigurator/Agent2MasterSecurityKillSwitch_disabled.yml
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/AdminWhitelistRuleConfigurator/Agent2MasterSecurityKillSwitch_enabled.yml
Labels: test
