Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-07, with the labels that each got.

#2046 build: Bump jenkins.version to 2.346.2
  integrations/pom.xml
Labels: dependencies

#2062 Drop commons-text API plugin temporarily
  plugin/pom.xml
Labels: bug

#2064 Add SystemPropertyLookup resolver to resolve java system properties
  plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java
  plugin/src/test/java/io/jenkins/plugins/casc/SecretSourceResolverTest.java
Labels: feature
