Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-05, with the labels that each got.

#1966 Test against LTS 2.332.3
  integrations/pom.xml
Labels: test

#1970 Initiate next LTS line 2.346.x
  integrations/pom.xml
Labels: dependencies

#1954 JENKINS-67371 Explicit the trust requirement for JCasC
  README.md
  docs/features/secrets.adoc
Labels: documentation

#1972 Demos - kubernetes - document more options
  demos/kubernetes/README.md
Labels: documentation
