Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2022-02, with the labels that each got.

#1848 update badges
  README.md
Labels: documentation

#1849 doc: rewrite JDK installation example using AdoptOpenJDK installer
  demos/jdk/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/JdkConfiguratorTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/JdkConfiguratorTestExpected.yml
Labels: documentation

#1850 doc: add examples for Maven configuration
  demos/maven/README.md
  demos/pipeline-maven/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalToolGlobalMavenTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/MavenConfiguratorTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalToolGlobalMavenTest.yaml
  integrations/src/test/resources/io/jenkins/plugins/casc/MavenConfiguratorTestExpected.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/MavenConfiguratorTestGlobalConfigExpected.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/MavenConfiguratorTestGlobalConfigSpecificFilesExpected.yml
Labels: documentation

#1889 Update jenkins.version to 2.319.3 LTS
  integrations/pom.xml
Labels: dependencies

#1904 Don't increment value outside of range when merging files
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategy.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategyTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/multiple-keys-a.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/multiple-keys-b.yml
Labels: bug

#1913 Replace deprecated APIs
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadAction.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/MergeStrategyAction.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/MergeStrategyFactory.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/ErrorOnConflictMergeStrategyTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/MergeStrategyTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategyTest.java
Labels: chore

#1917 Override merge issue with index
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategy.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategyTest.java
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/multiple-keys-a.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/multiple-keys-b.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/systemMessage-a.yml
  plugin/src/test/resources/io/jenkins/plugins/casc/yaml/systemMessage-b.yml
Labels: bug
