Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2023-08, with the labels that each got.

#2334 role-strategy-plugin assignments changed in new version of jenkins
  demos/role-strategy-auth/README.md
Labels: test

#2343 Update bom to latest version
  pom.xml
Labels: dependencies

#2315 chore: Parallelize Tests
  pom.xml
Labels: chore
