Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2023-12, with the labels that each got.

#2430 Strengthen test coverage of `JNLPLauncher`
  demos/build_agents/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/BuildAgentsTest.java
  test-harness/src/test/resources/io/jenkins/plugins/casc/core/ConfigureNodes.yml
Labels: test

#2431 Use json-api plugin
  plugin/pom.xml
  pom.xml
Labels: developer

#2433 Remove Crowd2 demo and integration test - suspended plugin
  demos/crowd2/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/Crowd2Test.java
Labels: developer

#2432 Remove outdated version conditionals
  plugin/src/main/java/io/jenkins/plugins/casc/ObsoleteConfigurationMonitor.java
  test-harness/src/test/java/io/jenkins/plugins/casc/BackwardCompatibilityTest.java
Labels: chore

#2437 Use joda-time as a test dependency
  integrations/pom.xml
Labels: test

#2440 Remove Bootstrap usages
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
Labels: enhancement

#2441 Adding test coverage for deprecated `JNLPLauncher.tunnel`
  demos/build_agents/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/BuildAgentsTest.java
Labels: test
