Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2023-09, with the labels that each got.

#2354 Use versions from plugin BOM
  integrations/pom.xml
  pom.xml
Labels: skip-changelog

#2357 Upgrade Role Strategy plugin to latest
  integrations/pom.xml
  integrations/src/test/resources/io/jenkins/plugins/casc/RoleStrategy1.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/RoleStrategy1Expected.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/RoleStrategy2.yml
Labels: test

#2362 Code cleanup
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/ModelConstructor.java
  pom.xml
Labels: developer

#2368 Upgrade plugin BOM and core baseline
  integrations/pom.xml
  plugin/pom.xml
  pom.xml
  test-harness/pom.xml
Labels: dependencies, java

#2372 update ec2 plugin tests
  demos/ec2/README.md
  integrations/pom.xml
  integrations/src/test/resources/io/jenkins/plugins/casc/alias1.yml
  plugin/pom.xml
  pom.xml
  test-harness/pom.xml
Labels: test
