Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2023-11, with the labels that each got.

#2407 SnakeYaml loader options to allow configuration of CodePointLimit for YAML input files
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationContext.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
  test-harness/src/test/java/io/jenkins/plugins/casc/YamlCodePointLimitTest.java
Labels: enhancement

#2352 Nicer error pages
  plugin/src/main/java/io/jenkins/plugins/casc/BaseConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCodeBootFailure.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfiguratorException.java
  plugin/src/main/java/io/jenkins/plugins/casc/UnknownAttributesException.java
  plugin/src/main/java/io/jenkins/plugins/casc/UnknownConfiguratorException.java
  plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/error.jelly
  plugin/src/test/java/io/jenkins/plugins/casc/ErrorPageTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/YamlMaxAliasesCollectionTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/impl/configurators/MissingConfiguratorTest.java
Labels: enhancement

#2384 Test with Java 21
  Jenkinsfile
Labels: chore

#2414 Improve git plugin and git client plugin examples
  Jenkinsfile
  demos/git-client/README.md
  demos/git/README.md
  demos/gitscm/README.md
  integrations/src/test/java/io/jenkins/plugins/casc/GitHostKeyVerificationTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/GitToolInstallationTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/GitscmTest.java
Labels: documentation

#2392 [JENKINS-64816] support for node monitors in CasC
  demos/node-monitors/README.md
  integrations/pom.xml
  integrations/src/test/java/io/jenkins/plugins/casc/core/NodeMonitorsConfiguratorTest.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/JenkinsConfigurator.java
Labels: documentation

#2418 Downgrade windows to Java 11 for CI
  Jenkinsfile
Labels: chore
