Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2023-03, with the labels that each got.

#2222 Switch to renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: chore

#2232 Update Job DSL to 1.82
  integrations/pom.xml
Labels: dependencies

#2234 Support forthcoming PCT multimodule mode
  Jenkinsfile
  integrations/pom.xml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalLibrariesGitHubTest.yml
  plugin/pom.xml
  pom.xml
  test-harness/pom.xml
  test-harness/src/test/java/io/jenkins/plugins/casc/CascJmhBenchmarkStateTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/ConfigurationAsCodeTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/SchemaGenerationSanitisationTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/impl/configurators/MissingConfiguratorTest.java
Labels: developer

#2238 Restore JSR 305 annotations
  plugin/pom.xml
Labels: bug

#2242 Upgrade parent POM from 4.56 to 4.57
  pom.xml
Labels: developer
