Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2024-08, with the labels that each got.

#2540 Update plugin baseline and BOM
  plugin/pom.xml
  pom.xml
  test-harness/pom.xml
Labels: dependencies, java

#2551 make plugin CSP compliant
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/reference.jelly
  plugin/src/main/webapp/css/reference.css
  test-harness/src/main/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: enhancement

#2552 stay compatible for PCT
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/resources/io/jenkins/plugins/casc/ConfigurationAsCode/index.jelly
  test-harness/src/main/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
Labels: developer
