Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2024-05, with the labels that each got.

#2489 Only load a secret which is a file
  plugin/src/main/java/io/jenkins/plugins/casc/impl/secrets/DockerSecretSource.java
Labels: bug

#2490 Require Jenkins 2.426.3 or newer
  integrations/pom.xml
  plugin/pom.xml
  pom.xml
  test-harness/pom.xml
Labels: developer

#2492 Restore jsr-305 dependency
  plugin/pom.xml
Labels: bug

#2493 Add JSR-305 dependency comment
  plugin/pom.xml
Labels: documentation

#2494 [JENKINS-73131] Adapt Configuration as Code for Jetty 12 (EE 8)
  plugin/src/test/java/io/jenkins/plugins/casc/MockHttpServletRequest.java
  plugin/src/test/java/io/jenkins/plugins/casc/TokenReloadCrumbExclusionTest.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/YamlSourceTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/MockHttpServletRequest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/MockHttpServletResponse.java
  test-harness/src/test/java/io/jenkins/plugins/casc/TokenReloadActionTest.java
Labels: developer
