Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2025-01, with the labels that each got.

#2601 Forbid `junit-dep` from `system-rules`
  test-harness/pom.xml
Labels: developer

#2622 Use versions from plugin BOM
  integrations/pom.xml
Labels: dependencies, java

#2624 Use `sonar` version from plugin BOM
  integrations/pom.xml
Labels: dependencies, java

#2625 Migrate from EE 8 to EE 9
  docs/PLUGINS.md
  docs/REQUIREMENTS.md
  plugin/src/main/java/io/jenkins/plugins/casc/CasCGlobalConfig.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCodeBootFailure.java
  plugin/src/main/java/io/jenkins/plugins/casc/TokenReloadCrumbExclusion.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java
  plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlUtils.java
  plugin/src/test/java/io/jenkins/plugins/casc/MockHttpServletRequest.java
  plugin/src/test/java/io/jenkins/plugins/casc/yaml/YamlSourceTest.java
  test-harness/src/test/java/io/jenkins/plugins/casc/JenkinsConfigTest.java
Labels: internal

#2623 Provide JUnit5 compatible alternative for RoundTripAbstractTest and RestartableJenkinsRule
  integrations/src/test/java/io/jenkins/plugins/casc/JobDslGlobalSecurityConfigurationTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/RoundTripMailerTest.java
  pom.xml
  test-harness/src/main/java/io/jenkins/plugins/casc/misc/RoundTripAbstractTest.java
  test-harness/src/main/java/io/jenkins/plugins/casc/misc/junit/jupiter/AbstractRoundTripTest.java
Labels: enhancement
