Repository jenkinsci/configuration-as-code-plugin, pull requests merged in 2025-04, with the labels that each got.

#2657 Allowing empty valued global variables in config file
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalNodePropertiesTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTestExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/core/GlobalNodePropertiesConfigurator.java
Labels: enhancement

#2663 Revert "Allowing empty valued global variables in config file"
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalNodePropertiesTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTestExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/core/GlobalNodePropertiesConfigurator.java
Labels: bug

#2666 Remove versions of plugins now managed in BOM
  integrations/pom.xml
Labels: skip-changelog

#2665 Allow empty valued variables without ignoring enviroment vars substitution
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalNodePropertiesTest.java
  integrations/src/test/java/io/jenkins/plugins/casc/GlobalNodePropertiesWithEnvVarsTest.java
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesTestExpected.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesWithEnvVarsTest.yml
  integrations/src/test/resources/io/jenkins/plugins/casc/GlobalNodePropertiesWithEnvVarsTestExpected.yml
  plugin/src/main/java/io/jenkins/plugins/casc/ConfigurationAsCode.java
  plugin/src/main/java/io/jenkins/plugins/casc/core/GlobalNodePropertiesConfigurator.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/CNode.java
  plugin/src/main/java/io/jenkins/plugins/casc/model/Scalar.java
Labels: enhancement
